// ============================================================
//  magics.js  ―  魔法データ定義
//  基礎魔法 / 特殊魔法 / 秘伝
//
//  range    : 射程マス数。null=射程なし、"全体"=全体、"任意"=任意
//  cost     : MPコスト式（文字列）
//  damage   : ダメージ式（文字列）。なければ null
//  duration : 効果継続ターン式（文字列）。なければ null
//  effect   : 効果説明（文字列）
//  clan     : 習得条件・一族制限など（文字列）。なければ null
//  eduCheck : EDU対抗値（数値）。なければ null（基礎魔法は不要）
//  learnTime: 習得時間式（文字列）。なければ null
// ============================================================

const MAGICS = {

  // ==================== 基礎魔法 ====================

  火: {
    name: "火",
    category: "基礎魔法",
    range: 2,
    cost: "1d6",
    damage: "1d6+MB",
    duration: null,
    effect: "火を操って1d6+MBダメージを与える。10ダメージ以上与えた場合、幸運%成功で相手に火傷を負わせることができる。",
    clan: "黒の一族は初期値4",
    eduCheck: null,
    learnTime: null,
  },

  水: {
    name: "水",
    category: "基礎魔法",
    range: 2,
    cost: "1d6",
    damage: "1d6+MB",
    duration: null,
    effect: "水を操って1d6+MBダメージを与える。「海洋学」「水泳」の代用が可能。",
    clan: "青の一族は初期値4",
    eduCheck: null,
    learnTime: null,
  },

  土: {
    name: "土",
    category: "基礎魔法",
    range: 2,
    cost: "1d6",
    damage: "1d6+MB",
    duration: null,
    effect: "土を操って1d6+MBダメージを与える。「地質学」の代用が可能。",
    clan: "黄の一族は初期値4",
    eduCheck: null,
    learnTime: null,
  },

  風: {
    name: "風",
    category: "基礎魔法",
    range: 2,
    cost: "1d6",
    damage: "1d6+MB",
    duration: null,
    effect: "風を操って1d6+MBダメージを与える。10ダメージ以上与えた場合、幸運%成功で相手を吹き飛ばしダメージを与えることができる。",
    clan: "翠の一族は初期値4",
    eduCheck: null,
    learnTime: null,
  },

  治癒: {
    name: "治癒",
    category: "基礎魔法",
    range: 2,
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "1d6+MB分、HPを回復させることができる。",
    clan: null,
    eduCheck: null,
    learnTime: null,
  },

  // ==================== 特殊魔法 ====================

  悪夢: {
    name: "悪夢",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "相手の勇気を1d6+MB減少させる。相手とのPOW対抗で勝利した場合、ランダムで発狂させることができる。",
    clan: null,
    eduCheck: 15,
    learnTime: "1d10時間",
  },

  いん石: {
    name: "いん石",
    category: "特殊魔法",
    range: 3,
    cost: "1d8",
    damage: "1d12+MB",
    duration: null,
    effect: "1d12+MBダメージのいん石を降らせ、使用者の縦3マス以内の敵全てに攻撃する。",
    clan: "星の一族(星飼い)は初期値4",
    eduCheck: 30,
    learnTime: "1d10時間",
  },

  解除: {
    name: "解除",
    category: "特殊魔法",
    range: 2,
    cost: "1d8",
    damage: null,
    duration: null,
    effect: "虚像や封印等の一部の魔法の効果を解く。特定の魔法には無効の場合がある。特殊魔法による状態異常は解除できるが、秘伝・禁止魔法・呪い・専用魔法などによるものは解除できない。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d10時間",
  },

  カウンター: {
    name: "カウンター",
    category: "特殊魔法",
    range: null,
    cost: "1d6",
    damage: null,
    duration: "2d3ターン",
    effect: "2d3ターンの間、相手から受けたダメージをそのまま跳ね返す。カウンターを成功させるには相手からダメージを受けなければならない。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d10時間",
  },

  ガゼラ: {
    name: "ガゼラ",
    category: "特殊魔法",
    range: 1,
    cost: "HP",
    damage: "最大HP消費分の固定値+DB",
    duration: null,
    effect: "最大HPを消費した分の固定ダメージ+DB。最大HPを削った分攻撃力が上がるが諸刃の剣。ガゼラ使いの一族もしくは体内にガゼラと共生している者しか使えない。",
    clan: "ガゼラ使いのみ",
    eduCheck: null,
    learnTime: null,
  },

  加速: {
    name: "加速",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "相手を2回行動、又は再行動させる。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d10時間",
  },

  眼識: {
    name: "眼識",
    category: "特殊魔法",
    range: "任意",
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "「目星」と同等の効果を持つ。また、特殊魔法「変身」を使用している相手とPOW対抗で勝利すれば、相手の「変身」を見破ることができる。",
    clan: null,
    eduCheck: 10,
    learnTime: "1d10時間",
  },

  虚像: {
    name: "虚像",
    category: "特殊魔法",
    range: 2,
    cost: "1d8",
    damage: null,
    duration: null,
    effect: "相手の命中値を2減少させる。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d10時間",
  },

  空間: {
    name: "空間",
    category: "特殊魔法",
    range: "任意",
    cost: "1d6",
    damage: null,
    duration: "1d3+MBターン",
    effect: "相手を1d3+MBターンの間、何処かの異空間・落とし穴に落とす。味方や敵を場から隔離することも可能。SIZ20以上のものは使用者のPOWと相手のHP値と対抗し勝利しなければ成功しない。",
    clan: null,
    eduCheck: 16,
    learnTime: "1d10時間",
  },

  結界: {
    name: "結界",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: null,
    duration: "1d3+MBターン",
    effect: "1d3+MBターンの間、2d4の装甲が付与される。結界による装甲の耐久値は特殊魔法「破壊」によってのみ耐久値が減少する。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d10時間",
  },

  氷: {
    name: "氷",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: "1d6+MB",
    duration: null,
    effect: "1d6+MBのダメージを与える。10ダメージ以上与えた場合、幸運成功で相手の回避を1減少させることができる。",
    clan: "白の一族は初期値4",
    eduCheck: 30,
    learnTime: "1d10時間",
  },

  重力: {
    name: "重力",
    category: "特殊魔法",
    range: "全体",
    cost: "1d10",
    damage: "固定1（毎ターン）",
    duration: "1d6+MBターン",
    effect: "1d6+MBターンの間、使用者以外の全てに固定1ダメージ。攻撃や反撃などで直接攻撃された場合、1d4ターンの間スタンとなる。",
    clan: null,
    eduCheck: 20,
    learnTime: "1d10時間",
  },

  心象: {
    name: "心象",
    category: "特殊魔法",
    range: null,
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "「心理学」の代用が可能。触れたものの思考や記憶を感じ取ることができる。また、幸運成功で狂気を一時的に抑えることもできる。",
    clan: "ナラトゥールの一族は初期値4",
    eduCheck: 16,
    learnTime: null, // INT対抗:16 も必要
  },

  聴音: {
    name: "聴音",
    category: "特殊魔法",
    range: "任意",
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "「聞き耳」と同等の効果を持つ。",
    clan: null,
    eduCheck: 10,
    learnTime: "1d10時間",
  },

  転移: {
    name: "転移",
    category: "特殊魔法",
    range: 5,
    cost: "1d8",
    damage: null,
    duration: null,
    effect: "1度訪れた場所に瞬間移動できる。5マス以内の敵の近くに瞬間移動し攻撃を仕掛けた場合、初めて攻撃を仕掛けた時に限り相手の回避値-5の奇襲を仕掛けられる。",
    clan: null,
    eduCheck: 24,
    learnTime: "1d10時間",
  },

  天空: {
    name: "天空",
    category: "特殊魔法",
    range: "全体",
    cost: "1d8",
    damage: null,
    duration: "1d20ターン",
    effect: "天候表の中から天候を指定し1d20ターンの間、指定した天候に変えることができる。",
    clan: "星の一族(空飼い)は初期値4",
    eduCheck: 30,
    learnTime: "1d10時間",
  },

  破壊: {
    name: "破壊",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: "1d6+MB",
    duration: null,
    effect: "1d6+MBダメージを与える。装甲にダメージを与え破壊した場合、そのまま敵本体にダメージを与えることができる。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d10時間",
  },

  爆破: {
    name: "爆破",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: "1d6+MB（火傷による2ダメージを1d6ターン追加）",
    duration: null,
    effect: "ダメージを1d6+MB、火傷による2ダメージを1d6ターン与える。爆破対象の周り2マス以内の者にも火傷を負わせ、与えたダメージ値と相手のCONと対抗で勝利すれば2マス吹き飛ばすことができる。",
    clan: null,
    eduCheck: 18,
    learnTime: "1d8時間",
  },

  封印: {
    name: "封印",
    category: "特殊魔法",
    range: 2,
    cost: "1d8",
    damage: null,
    duration: "1d3+1+MBターン",
    effect: "1d3+1ターン+MBターンの間、相手をスタンさせる。スタンターン中、行動するためには1d100でCON×3に成功しなければならない。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d4時間",
  },

  浮遊: {
    name: "浮遊",
    category: "特殊魔法",
    range: "単体",
    cost: "1d6",
    damage: null,
    duration: "1d10+MBターン",
    effect: "1d10+MBターンの間、飛兵となる。空を飛び、飛翔することができる。",
    clan: null,
    eduCheck: 15,
    learnTime: "1d10時間",
  },

  付与: {
    name: "付与",
    category: "特殊魔法",
    range: 2,
    cost: "任意",
    damage: null,
    duration: null,
    effect: "自分のHPかMPを任意で減少させた分、相手のHPかMPにそのままの数値を付与できる。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d4時間",
  },

  分霊: {
    name: "分霊",
    category: "特殊魔法",
    range: null,
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "自分の分身を作ることができるが、勇気が1d6減少する。分霊は本体とHP・MPが共有され、分霊もしくは本体が倒されるか本体の任意で解除される。初期値はLv。",
    clan: null,
    eduCheck: 20,
    learnTime: "1d4時間",
  },

  変身: {
    name: "変身",
    category: "特殊魔法",
    range: 2,
    cost: "1d8",
    damage: null,
    duration: null,
    effect: "自分もしくは相手を違う姿に変身させることができる。種族・性別まで見た目だけなら変身させることができる。ステータスは使用者本来のもの。特殊魔法「眼識」やその効果のある魔導具には見破られてしまうことがある。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d6時間",
  },

  補助: {
    name: "補助",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "特技・魔法の成功値に+1の補正がつく。",
    clan: null,
    eduCheck: 14,
    learnTime: "1d6時間",
  },

  模倣: {
    name: "模倣",
    category: "特殊魔法",
    range: 2,
    cost: "1d8",
    damage: null,
    duration: "1d3+MBターン",
    effect: "1d3+MBターンの間、相手の使用した魔法を真似して放つことができる。ただし、秘伝や禁止魔法、専用魔法は模倣できない。",
    clan: null,
    eduCheck: 16,
    learnTime: "1d8時間",
  },

  誘惑: {
    name: "誘惑",
    category: "特殊魔法",
    range: 2,
    cost: "1d6",
    damage: null,
    duration: null,
    effect: "異性のみ有効。誘惑された者は勇気%成功で行動可能。勇気%失敗でスタンとなる。",
    clan: null,
    eduCheck: 12,
    learnTime: "1d10時間",
  },

  // ==================== 秘伝 ====================

  明鏡: {
    name: "明鏡",
    category: "秘伝",
    range: "単体",
    cost: "1d10",
    damage: null,
    duration: null,
    effect: "自力で自分の発狂を解除し、心労を1つ回復できる。",
    clan: "青の一族 / 基礎魔法「水」:9以上で会得",
    eduCheck: null,
    learnTime: null,
  },

  製鉄: {
    name: "製鉄",
    category: "秘伝",
    range: "単体",
    cost: "1d10",
    damage: "相手のHPから1d6の攻撃力を得る",
    duration: null,
    effect: "相手のHPから1d6の攻撃力を得る。ガゼラによって作られた鉄は戦闘終了時に消滅する。",
    clan: "ガゼラ使いのみ",
    eduCheck: null,
    learnTime: null,
  },

  忘却: {
    name: "忘却",
    category: "秘伝",
    range: "単体",
    cost: "1d10",
    damage: null,
    duration: null,
    effect: "指定した事柄を完全に忘れさせることができる。術を掛けられた相手は、その事象に関するあらゆる記憶や感情を思い出すことはできない。",
    clan: "ナラトゥール / 特殊魔法「心象」:9以上",
    eduCheck: null,
    learnTime: null,
  },

  劇薬: {
    name: "劇薬",
    category: "秘伝",
    range: "単体",
    cost: "1d10",
    damage: null,
    duration: null,
    effect: "「神の雫・涙」と「神の雫・血」を混ぜ合わせることで、毒薬を回復薬に、回復薬を毒薬へと効果を入れ替えることができる。入れ替えた時に液体は紫色に変色し、どんな魔法であっても効果を知ることはできない。",
    clan: "「神の雫・涙」と「神の雫・血」を所持",
    eduCheck: null,
    learnTime: null,
  },

  石化: {
    name: "石化",
    category: "秘伝",
    range: 2,
    cost: "1d10",
    damage: null,
    duration: "永久（解除まで）",
    effect: "触れた物を石に変える。POW対抗に勝利すれば、使用者が解除しない限り永久スタンさせることができる。",
    clan: "黄の一族 / 基礎魔法「土」:9以上",
    eduCheck: null,
    learnTime: null,
  },

  吸血: {
    name: "吸血",
    category: "秘伝",
    range: "単体",
    cost: "1d10",
    damage: "1d20+DB",
    duration: null,
    effect: "相手へ接触、1d20+DBダメージを与える。与えたダメージ分HPが回復する。",
    clan: "吸血鬼のみ",
    eduCheck: null,
    learnTime: null,
  },

  黒炎: {
    name: "黒炎",
    category: "秘伝",
    range: 2,
    cost: "1d10",
    damage: "1d6+MB（永久火傷追加）",
    duration: null,
    effect: "1d6+MBダメージを与え、攻撃した相手とその中心3マス以内の全ての敵に永久火傷ダメージを与える。",
    clan: "黒の一族 / 基礎魔法「火」:9以上",
    eduCheck: null,
    learnTime: null,
  },

  凍結: {
    name: "凍結",
    category: "秘伝",
    range: 2,
    cost: "1d10",
    damage: "1d6+MB",
    duration: "1d3ターン（スタン）",
    effect: "1d6+MBダメージを与え、ダメージを受けた相手とその中心3マス内にいるもの全てを1d3ターンの間スタンさせる。",
    clan: "白の一族 / 特殊魔法「氷」:9以上",
    eduCheck: null,
    learnTime: null,
  },

  疾風: {
    name: "疾風",
    category: "秘伝",
    range: "全体",
    cost: "1d10",
    damage: null,
    duration: null,
    effect: "戦闘ラウンド時に味方全員を2回行動あるいは再行動させることができる。",
    clan: "翠の一族 / 基礎魔法「風」:9以上",
    eduCheck: null,
    learnTime: null,
  },

  星読み: {
    name: "星読み",
    category: "秘伝",
    range: null,
    cost: "1d10",
    damage: null,
    duration: null,
    effect: "占星術をして少し先の未来を予測することができる。また「天文学」の代用も可能。",
    clan: "星の一族(星飼い) / 特殊魔法「隕石」:9以上",
    eduCheck: null,
    learnTime: null,
  },

  大嵐: {
    name: "大嵐",
    category: "秘伝",
    range: "全体",
    cost: "1d10",
    damage: null,
    duration: "1d6ターン",
    effect: "1d6ターンの間、「嵐」「豪雨」「竜巻」のどれかを指定し天候を変化させる。",
    clan: "星の一族(空飼い) / 特殊魔法「天空」:9以上",
    eduCheck: null,
    learnTime: null,
  },

  祈り: {
    name: "祈り",
    category: "秘伝",
    range: null,
    cost: null,
    damage: null,
    duration: null,
    effect: "旧世界の事象に関わっても、心労ポイントが増えない。また、旧世界の事象に関わった時のみ、幸運%成功で発狂を回避できる。",
    clan: "天使の落胤のみ",
    eduCheck: null,
    learnTime: null,
  },

  完全結界: {
    name: "完全結界",
    category: "秘伝",
    range: "任意",
    cost: "1d10",
    damage: "1d6+5（接近戦時）",
    duration: null,
    effect: "特定の対象1人を完全に攻撃から守る。接近戦の場合ダメージ1d6+5を与える。MP9以下で使用しMPが0になった場合リーハスの憑依後、自分の現在のステータスとの差分勇気の最大値が減少する。",
    clan: "リーハスの落し子 / 冒険者による詠唱",
    eduCheck: null,
    learnTime: null,
  },

};

// エクスポート（モジュール環境の場合）
// export default MAGICS;
