const assert = require('node:assert/strict');
const { initialState, reduce, forecastFor } = require('./model');
let s = initialState();
assert.equal(s.selected, 'arshe');
const moved = reduce(s, { type: 'MOVE', position: [520, 340] });
assert.deepEqual(s.positions.arshe, [535, 345]);
assert.deepEqual(moved.positions.arshe, [520, 340]);
s = reduce(moved, { type: 'FORECAST', id: 'guard' });
assert.equal(s.phase, 'forecast');
assert.deepEqual(forecastFor(s).attacker.name, 'アルシェ');
assert.equal(forecastFor(s).defenderAfter, 0);
assert.equal(forecastFor(s).counter, false);
assert.deepEqual(reduce(s, { type: 'CANCEL' }).positions.arshe, [520, 340]);
s = reduce(s, { type: 'CONFIRM' });
assert.equal(s.phase, 'attacking');
assert.equal(reduce(s, { type: 'SELECT', id: 'mage' }), s);
s = reduce(s, { type: 'FINISH' });
assert.equal(s.phase, 'normal');
assert.ok(s.defeated.includes('guard'));
assert.equal(reduce(s, { type: 'FORECAST', id: 'guard' }), s);
s = reduce(s, { type: 'SELECT', id: 'mage' });
s = reduce(s, { type: 'FORECAST', id: 'sentinel' });
assert.equal(forecastFor(s).defenderAfter, 6);
assert.equal(forecastFor(s).counter, true);
assert.equal(forecastFor(s).attackerAfter, 14);
s = reduce(reduce(s, { type: 'CONFIRM' }), { type: 'FINISH' });
assert.equal(s.enemyHp.sentinel, 6);
assert.equal(s.allyHp.mage, 14);
assert.equal(forecastFor(reduce(s, { type: 'FORECAST', id: 'sentinel' })).defenderAfter, 0);
assert.equal(reduce(s, { type: 'ROSTER' }).rosterOpen, false);
assert.deepEqual(reduce(s, { type: 'RESET' }), initialState());
console.log('silver-battle-ui: mock state tests passed');
