// 静的参照・DOM代替の単体テスト。ブラウザ描画検査ではない。
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const model=require('./home-model.js'),{mount}=require('./home.js');
const apps=require('../太陽盤_コマンド試作01/menu-apps-model.js'),wheel=require('../太陽盤_コマンド試作01/menu-preview-model.js');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),css=fs.readFileSync(path.join(__dirname,'home.css'),'utf8');
for(const [,ref] of html.matchAll(/(?:src|href)="([^"]+)"/g))assert.ok(fs.existsSync(path.resolve(__dirname,ref.replaceAll('&amp;','&').split(/[?#]/)[0])),ref);
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);
for(const file of ['home.js','home-model.js'])new vm.Script(fs.readFileSync(path.join(__dirname,file),'utf8'));
assert.equal([...html.matchAll(/data-home-app="/g)].length,5);
assert.ok(!html.includes('src="../太陽盤_コマンド試作01/menu-preview.js'),'旧説明チップ処理を二重に読み込まない');
assert.ok(!html.includes('class="dock"'),'大きなドック箱を置かない');
assert.ok(css.includes('.independent-apps')&&css.includes('background:transparent; border:0;'));
function rule(selector) {
  const prefix=selector+' {';return css.slice(css.indexOf(prefix)+prefix.length,css.indexOf('}',css.indexOf(prefix)));
}
const artRule=rule('.app-art'),timeRule=rule('.home-time');
const commandSource=fs.readFileSync(path.join(__dirname,'../太陽盤_コマンド試作01/layout.html'),'utf8');
const commandFont=commandSource.match(/\.command \{[^}]*font-family:\s*([^;]+);/)[1].replace(/\s/g,'');
const homeFont=css.match(/--home-font:([^;]+);/)[1].replace(/\s/g,'');
assert.equal(homeFont,commandFont,'ホームと太陽盤コマンドのフォント・フォールバック順を一致させる');
assert.ok(rule('.independent-home').includes('font-family:var(--home-font);')&&rule('.independent-home').includes('font-synthesis:none;'));
assert.ok(rule('.notice-beta').includes('var(--home-font)')&&rule('.app-metric').includes('var(--home-font)'),'上書きされる小文字も統一');
assert.ok(rule('#home-dialog').includes('font-family:var(--home-font);'),'iframe外の詳細画面も統一');
assert.ok(!css.includes('Consolas')&&!css.includes("'Yu Gothic UI'"),'ホーム専用CSSの書体の混在をなくす');
assert.ok(artRule.includes('width:64px; height:64px;'),'下地の基本サイズは変えない');
assert.ok(artRule.includes('border-radius:0;')&&artRule.includes('background:rgb(13 15 17 / .6);'),'透ける黒の正方形');
assert.ok(artRule.includes('box-shadow:var(--app-backing-offset) var(--app-backing-offset) 0 0 var(--app-backing-color);'),'金は右下へずれた平坦な下地だけ');
assert.ok(css.includes('--app-backing-offset:4px;')&&css.includes('--app-backing-color:#d3ad59;'));
assert.ok(timeRule.includes('border:0;')&&timeRule.includes('background:transparent;')&&timeRule.includes('box-shadow:none;'),'時間帯アイコンの囲いを外す');
assert.ok(timeRule.includes('width:110px; height:38px;')&&timeRule.includes('padding:3px 6px;'),'時間帯の絵の表示寸法を維持');
const wallpaper=fs.readFileSync(path.join(__dirname,'home-wallpaper-stars-v01.png'));
assert.equal(wallpaper.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
assert.equal(wallpaper.readUInt32BE(16),1844);assert.equal(wallpaper.readUInt32BE(20),853);
assert.ok(Math.abs(1844/853-844/390)<.003,'生成素材は横844×390とほぼ同じ比率');
assert.ok(html.includes('href="home-wallpaper-stars-v01.png"'),'元の背景は保存リンクから参照できる');
assert.ok(!html.includes('src="home-wallpaper-stars-v01.png'),'元の全面背景を重ねて色を隠さない');
assert.ok(!html.includes('class="home-shade"'),'隅の装飾を旧写真用の色かぶせで暗くしない');
assert.ok(rule('.home-corners').includes('pointer-events:none;'),'隅飾りは操作を遮らない');
assert.equal([...html.matchAll(/class="home-corner home-corner-/g)].length,4,'同じ透過飾りを四隅へ反転して置く');
assert.ok(rule('.home-corner').includes("filter:url('#home-corner-tint');")&&html.includes('in2="SourceAlpha" operator="in"'),'PNGのアルファを保って隅飾りだけ色替え');
assert.ok(rule('.independent-home').includes('background:var(--home-surface,#1c1d1f);'),'画像なしでも持ち主の下地色');
assert.ok(rule('.independent-home[data-app-names="false"] .app-name').includes('visibility:hidden;'),'名前OFFでも配置とタップ範囲を保つ');
assert.ok(html.includes('id="home-app-names" type="checkbox" checked'),'名前は初期ONの比較操作');
const cornerAsset=fs.readFileSync(path.join(__dirname,'home-corner-star-mask-v01.png'));
assert.equal(cornerAsset.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(cornerAsset[25],6,'隅飾りはRGBA');
assert.deepEqual(model.theme('alche'),{background:'#1c1d1f',backing:'#d3ad59',ornament:'#b9ad8c',text:'#eceff2'});
assert.deepEqual(model.theme('karima'),{background:'#e7eef3',backing:'#7194ae',ornament:'#142a48',text:'#000000'});
const authorSettings=model.readSettings(fs.readFileSync(path.join(__dirname,'home-settings-author-20261009.json'),'utf8'));
assert.deepEqual(authorSettings.ownerThemes.karima.light,model.theme('karima'),'原作者指定ファイルと新しい初期色を一致させる');
assert.deepEqual(authorSettings.ownerThemes.alche.dark,model.theme('alche'));assert.deepEqual(authorSettings.ownerThemes.karima.dark,model.theme('karima',{},'dark'));
assert.equal(authorSettings.selectedOwner,'karima');assert.equal(authorSettings.preview.noticeKind,'encounter');assert.equal(authorSettings.preview.frame,false);
assert.equal(authorSettings.corner.size,36);assert.equal(authorSettings.corner.inset,0);assert.equal(authorSettings.showAppNames,true);
assert.deepEqual(model.theme('karima',{},'dark'),{background:'#181c22',backing:'#a8bac7',ornament:'#97a8ba',text:'#eceff2'});
assert.equal(model.themeMode('alche','light'),'dark');assert.equal(model.themeMode('karima','light'),'light');assert.equal(model.themeMode('karima','dark'),'dark');
assert.equal(model.themeMode('__proto__','light'),'dark');assert.equal(model.themeMode('karima','invalid'),'light');
assert.equal(model.theme('__proto__',{backing:'url(bad)'}).backing,'#d3ad59');
assert.equal(model.theme('karima',{background:'#ABCDEF'}).background,'#abcdef');
assert.equal(model.theme('karima',null).background,'#e7eef3');
assert.equal(model.theme('karima',{text:'url(bad)'}).text,'#000000');
const lightRule=rule('.independent-home[data-owner="karima"][data-theme-mode="light"]');
assert.ok(lightRule.includes('--notice-surface:#e9eef3;')&&lightRule.includes('--app-label-ink:var(--home-ink);')&&lightRule.includes('--app-label-shadow:none;'),'明るい下地に暗い文字、名前の影を外す');
assert.ok(rule('.home-notice').includes('background:var(--notice-surface,rgb(13 15 17 / .86));')&&rule('.home-notice:hover').includes('var(--notice-hover'),'帯の通常・hoverをセットで切替');
assert.ok(rule('.map-caption small').includes('color:#bcc6cb;')&&rule('.app-metric').includes('color:#f0f1ec;'),'暗い面に残す文字まで青墨にしない');
function luminance(hex) {
  const linear=hex.slice(1).match(/../g).map(value=>parseInt(value,16)/255).map(value=>value<=.04045?value/12.92:((value+.055)/1.055)**2.4);
  return linear[0]*.2126+linear[1]*.7152+linear[2]*.0722;
}
function contrast(a,b) { const values=[luminance(a),luminance(b)].sort((x,y)=>y-x);return (values[0]+.05)/(values[1]+.05); }
const lightTheme=model.theme('karima'),cssColor=key=>lightRule.match(new RegExp('--'+key+':(#[0-9a-f]{6});'))[1];
for(const [ink,surface] of [[lightTheme.text,lightTheme.background],[lightTheme.text,cssColor('notice-surface')],[cssColor('home-muted'),lightTheme.background],[cssColor('home-accent'),cssColor('notice-surface')],[cssColor('notice-beta-ink'),cssColor('notice-surface')]]) {
  assert.ok(contrast(ink,surface)>=4.5,'初期色の不透明な面／文字の計算値4.5:1以上（描画の実測ではない）');
}
assert.equal(model.ornamentSize(23),36);assert.equal(model.ornamentSize(64),64);assert.equal(model.ornamentInset(25),0);assert.equal(model.ornamentInset(12),12);
assert.ok(rule('.home-right').includes('left:338px; top:0px; width:494px; height:390px;'),'生成見本の配置変更は取り込まない');
assert.ok(rule('.home-map').includes('top:82px; width:494px; height:190px;'),'マップ位置・サイズを維持');
assert.ok(rule('.home-map-open').includes('inset:0; width:100%; height:100%;'),'マップの窓全体を一つのボタンにする');
assert.ok(html.includes('id="map-open"')&&html.includes('aria-label="マップの入口を開く"'),'矢印だけでも入口名は読上げに残す');
assert.ok(!html.includes('<span class="map-go">出撃／探索</span>'),'白い出撃／探索札を撤去');
assert.ok(html.includes('<svg class="map-go" viewBox="0 0 24 24" aria-hidden="true" focusable="false">'),'矢印は独立した操作対象にしない');
assert.ok(rule('.map-go').includes('width:18px; height:18px;')&&rule('.map-go').includes('stroke:#d3ad59;')&&rule('.map-go').includes('fill:none;'),'小さな金の線だけの矢印');
assert.ok(!rule('.map-go').includes('background:')&&rule('.map-go').includes('pointer-events:none;'),'矢印の札下地はなく、クリックを遮らない');
assert.ok(rule('.home-map-open:focus-visible').includes('outline:2px solid #d3ad59;'),'キーボード操作中は入口を見失わない');
assert.ok(html.includes('class="home-map-frame"')&&html.includes('src="map-frame-silver-gold-v01.png?v=20261008a"'),'景色と飾り枠の別素材');
const frameAsset=fs.readFileSync(path.join(__dirname,'map-frame-silver-gold-v01.png'));
assert.equal(frameAsset.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
assert.equal(frameAsset.readUInt32BE(16),2022);assert.equal(frameAsset.readUInt32BE(20),778);assert.equal(frameAsset[25],6,'透過を保持したRGBA');
assert.ok(rule('.home-map>.home-map-frame').includes('pointer-events:none;'),'枠の画像で入口のクリックを遮らない');
assert.ok(rule('.home-map[data-loading="true"]>#home-location').includes('opacity:0;'),'背景だけを隠し、枠は読み込み状態で消さない');
assert.ok(html.includes('id="notice-viewport" aria-hidden="true"'),'本文の複製は読上げ対象から外す');
assert.ok(!html.includes('id="notice-period"')&&!css.includes('.notice-period'),'右端の種類欄を外し、その幅と余白を本文へ戻す');
assert.ok(rule('.notice-viewport').includes('flex:1;')&&rule('.notice-heading').includes('flex:none;'),'本文が残りの幅を使い、見出しとβは縮めない');
assert.ok(css.includes('transform:translateX(var(--ticker-offset,0px));'),'移動はtransformのみ');
assert.ok(!html.includes('id="notice-repeat"')&&!css.includes('@keyframes fortune-ticker'),'複製による無限スクロールを使わない');
assert.ok(css.includes('.home-notice .notice-track { transform:none;'),'OSの動きを減らす設定は静止');
assert.ok(!html.includes('<marquee'),'非推奨のmarquee要素を使わない');
const longPlan={distance:120,duration:120/28,before:5,after:3,total:8+120/28};
assert.deepEqual(model.ticker(420,300),longPlan);
assert.deepEqual(model.ticker(90,300),{distance:0,duration:0,before:5,after:3,total:8},'短文は読む間だけ静止');
assert.equal(model.ticker(300,300).distance,0,'ぴったり収まる文も静止');
assert.deepEqual(model.tickerState(longPlan,4),{phase:'before',offset:0,done:false});
assert.deepEqual(model.tickerState(longPlan,6),{phase:'scroll',offset:-28,done:false});
assert.deepEqual(model.tickerState(longPlan,10),{phase:'after',offset:-120,done:false});
assert.equal(model.tickerState(longPlan,longPlan.total).done,true);
assert.deepEqual(model.tickerState(model.ticker(90,300),7),{phase:'reading',offset:0,done:false});
assert.equal(model.nextForecast('encounter'),'story');assert.equal(model.nextForecast('none'),'story');
assert.deepEqual(model.forecastOrder,['story','sale','support','encounter']);
assert.equal(model.ticker(420,300,2,4).total,6+120/28);
assert.equal(model.readingSeconds('',5),5);assert.equal(model.readingSeconds(99,3),3);
assert.equal(model.noticeFontSize(290,300),13.5,'収まる文は元の大きさを維持');
assert.equal(model.noticeFontSize(310,300),13,'少しだけはみ出す文は0.1px単位で調整');
assert.equal(model.noticeFontSize(450,300),12,'長文でも12pxより小さくしない');
assert.equal(model.noticeFontSize(100,300,12.5),12.5,'選んだ上限を守る');
assert.equal(model.noticeFontLimit(11),13.5);assert.equal(model.noticeFontLimit(14),13.5);assert.equal(model.noticeFontLimit(''),13.5);
for(const width of [0,NaN,Infinity])assert.equal(model.noticeFontSize(width,300),13.5,'未計測では無理に縮めない');
assert.ok(rule('.notice-copy').includes('font-size:var(--ticker-font,13.5px);'),'サイズ変更は本文だけ');
assert.ok(rule('.notice-measure').includes('visibility:hidden;')&&rule('.notice-measure').includes('position:absolute;'),'測定用の文字は表示・配置に混ぜない');
assert.ok(html.includes('id="notice-font-auto" type="checkbox" checked'),'自動調整の初期値はON');
for(const [text,viewport] of [[0,300],[420,0],[-1,300],[NaN,300],[Infinity,300],[420,NaN]])assert.equal(model.ticker(text,viewport),null);
// CSS配置の数値確認。ブラウザでの実測ではない。
const slotWidth=(494-8*4)/5,artExtent=64+4;
assert.ok(artExtent<slotWidth,'金の張り出しを含めても隣のアプリに重ならない');
assert.ok(282+64+9+14*1.35<=390,'名前を金の下地から離しても横画面内に収まる');
assert.ok(!/\b\d{1,2}:\d{2}\b/.test(html+JSON.stringify(model.owners)+JSON.stringify(model.forecasts)),'時計時刻を表示しない');
assert.ok(!/<iframe id="home-fortune"[^>]*\ssrc=/.test(html),'閉じた予報を最初に読み込まない');
assert.ok(html.includes('残金 —')&&html.includes('名声 —'));
assert.equal(model.owner('__proto__'),'alche');assert.equal(model.owner('karima'),'karima');
assert.equal(model.presentation('karima','prologue','sale').from,'アルシェ');
for(const kind of Object.keys(model.forecasts)) {
  const result=model.presentation('alche','after',kind);assert.equal(result.after,true);assert.equal(result.period,model.forecasts[kind].label);assert.equal(result.from,'運命予報');
  assert.equal(result.task,'届いたタスクを確認する','予報の種類を変えてもマップの目的は変えない');
}
assert.equal(model.presentation('alche','after','__proto__').copy,model.forecasts.story.copy);
assert.equal(model.forecast('__proto__').key,'story');
assert.equal(model.fit(844,390),1);assert.ok(model.fit(390,844)<1);assert.ok(model.fit(844,390,true)<1);
function node() {return {dataset:{},handlers:new Map(),hidden:false,attributes:{},style:{properties:{},setProperty(k,v){this.properties[k]=v;}},addEventListener(t,f){if(!this.handlers.has(t))this.handlers.set(t,new Set());this.handlers.get(t).add(f);},removeEventListener(t,f){this.handlers.get(t)?.delete(f);},emit(t,event={}){for(const f of [...this.handlers.get(t)||[]])f(event);},async emitAsync(t,event={}){await Promise.all([...this.handlers.get(t)||[]].map(f=>f(event)));},focus(){this.focused=true;},select(){this.selected=true;},append(item){this.appended=item;},click(){this.clicked=true;this.emit('click');},remove(){this.removed=true;},getAttribute(k){return this.attributes[k];},setAttribute(k,v){this.attributes[k]=v;},removeAttribute(k){delete this.attributes[k];},querySelectorAll(){return [];},getBoundingClientRect(){return {width:844};}};}
function setup(native=true,wallpaperReady=null,fontWidth=null,storageOptions={}) {
  const items=new Map(),byId=id=>{if(id==='notice-period')return null;if(!items.has(id))items.set(id,node());return items.get(id);};
  const doc=node(),win=node();doc.body=node();doc.hidden=false;doc.getElementById=byId;
  const storage=storageOptions.data||new Map(),writes=[];
  const localStorage={getItem(key){if(storageOptions.readFail)throw new Error('storage denied');return storage.get(key)||null;},setItem(key,value){if(storageOptions.writeFail)throw new Error('storage denied');storage.set(key,value);writes.push([key,value]);}};
  if(storageOptions.getterFail)Object.defineProperty(win,'localStorage',{get(){throw new Error('SecurityError');}});else win.localStorage=localStorage;
  const elements=[],urls=new Map(),revoked=[],timers=new Map();let urlId=0,timerId=0;
  doc.createElement=tag=>{const element=node();element.tagName=tag;elements.push(element);return element;};
  win.Blob=Blob;win.URL={createObjectURL(blob){const url='blob:settings-'+(++urlId);urls.set(url,blob);return url;},revokeObjectURL(url){revoked.push(url);urls.delete(url);}};
  win.setTimeout=fn=>{timers.set(++timerId,fn);return timerId;};win.clearTimeout=id=>timers.delete(id);
  win.flushTimeouts=()=>{for(const [id,fn] of [...timers]){timers.delete(id);fn();}};
  const frames=new Map();let frameId=0,clock=0;
  win.requestAnimationFrame=fn=>{frames.set(++frameId,fn);return frameId;};win.cancelAnimationFrame=id=>frames.delete(id);
  win.step=ms=>{clock+=ms;const callbacks=[...frames.values()];frames.clear();callbacks.forEach(fn=>fn(clock));};win.pendingFrames=()=>frames.size;
  win.innerWidth=844;win.innerHeight=390;win.location={protocol:'http:',origin:'http://localhost:8931',search:''};
  const media=Object.assign(node(),{matches:false});win.matchMedia=()=>media;
  byId('menu-character').value='alche';byId('menu-phase').value='evening';byId('home-stage').value='prologue';byId('notice-kind').value='story';
  byId('menu-effects').checked=true;byId('home-mystery').checked=true;byId('menu-show-frame').checked=false;
  byId('home-app-names').checked=true;byId('home-corner-size').value='36';byId('home-corner-inset').value='0';
  byId('notice-scroll').checked=true;byId('notice-viewport').clientWidth=300;byId('notice-copy').offsetWidth=420;
  byId('notice-before').value='5';byId('notice-after').value='3';
  // 従来の仮想時計は縮小OFFで同じ移動距離を検査。別ケースはフォントに比例する実幅を模擬。
  byId('notice-font').value='13.5';byId('notice-font-auto').checked=fontWidth!==null;
  if(fontWidth!==null) {
    let naturalWidth=fontWidth;
    Object.defineProperty(byId('notice-copy'),'offsetWidth',{get(){return Math.ceil(naturalWidth*(parseFloat(this.style.properties['--ticker-font'])||13.5)/13.5);},set(value){naturalWidth=value;}});
    Object.defineProperty(byId('notice-measure'),'offsetWidth',{get(){return Math.ceil(naturalWidth*(parseFloat(this.style.properties['--ticker-base-font'])||13.5)/13.5);}});
  } else Object.defineProperty(byId('notice-measure'),'offsetWidth',{get(){return byId('notice-copy').offsetWidth;}});
  const sent=[];byId('menu-wheel').contentWindow={postMessage(m){sent.push(m);}};
  const buttons=Object.keys(apps.apps).map(id=>{
    const button=id==='ouroboros'?byId('home-ouroboros'):node();button.dataset.homeApp=id;button.art=node();button.img=node();button.fallback=node();
    button.art.querySelector=()=>button.img;button.querySelector=selector=>selector==='.app-art'?button.art:button.fallback;return button;
  });
  const mapButtons=['exploration','battle','encounter'].map(id=>Object.assign(node(),{dataset:{mapMode:id}}));
  const forecastButtons=Object.keys(model.forecasts).map(id=>Object.assign(node(),{dataset:{forecastKind:id}}));
  doc.querySelectorAll=selector=>selector==='[data-home-app]'?buttons:selector==='[data-forecast-kind]'?forecastButtons:mapButtons;
  const sticker=node();byId('home-beta').querySelector=()=>sticker;
  if(wallpaperReady!==null){byId('home-corner-source').complete=true;byId('home-corner-source').naturalWidth=wallpaperReady?1280:0;}
  byId('home-fortune').dataset.src='../運命予報_分離素材01/layers-preview.html?embed=menu&v=20261005a';
  const dialog=byId('home-dialog');if(native){dialog.showModal=function(){this.open=true;};dialog.close=function(){this.open=false;this.emit('close');};}
  const time={validPhase:p=>['morning','day','evening','night'].includes(p),phases:{morning:{label:'朝'},day:{label:'昼'},evening:{label:'夕方'},night:{label:'夜'}},icon:p=>p};
  const api=mount(doc,win,model,apps,wheel,time);return {api,doc,win,byId,sent,buttons,mapButtons,forecastButtons,sticker,media,storage,writes,elements,urls,revoked,timers};
}
const s=setup();assert.equal(s.byId('menu-device').dataset.frame,'false');assert.equal(s.byId('home-fortune').src,undefined);
for(const [key,value] of Object.entries({size:'40%',x:'78%',y:'21%',angle:'18deg'}))assert.equal(s.byId('menu-screen').style.properties['--app-beta-'+key],value);
assert.equal(apps.beta.size,33,'素材比較ページの保存値は変えない');
assert.equal(s.byId('notice-from').textContent,'カリマ');
assert.equal(s.byId('notice-beta').hidden,true);
assert.equal(s.byId('home-notice').dataset.scrolling,'false','プロローグの通信は流さない');
s.byId('home-notice').emit('click');assert.equal(s.byId('home-dialog-title').textContent,'カリマからのメッセージ');assert.equal(s.byId('home-fortune').src,undefined);
s.byId('menu-character').value='karima';s.byId('menu-character').emit('change');assert.equal(s.byId('notice-from').textContent,'アルシェ');assert.equal(s.byId('menu-screen').dataset.owner,'karima');
s.byId('home-stage').value='after';s.byId('home-stage').emit('change');assert.equal(s.byId('notice-kind-control').hidden,false);
assert.equal(s.byId('home-notice').dataset.scrolling,'true');
assert.equal(s.byId('notice-track').style.properties['--ticker-offset'],'0px');
assert.equal(s.byId('home-notice').dataset.tickerPhase,'before');
assert.ok(s.byId('home-notice').attributes['aria-label'].includes(model.forecasts.story.copy),'読み上げは完全な文を一度だけ');
assert.ok(s.byId('home-notice').attributes['aria-label'].includes(model.forecasts.story.label),'種類は帯の読み上げ名に残す');
s.byId('home-dialog').close();assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'running');
s.byId('notice-scroll').checked=false;s.byId('notice-scroll').emit('change');assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'paused');
s.byId('notice-scroll').checked=true;s.byId('notice-scroll').emit('change');assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'running');
s.doc.hidden=true;s.doc.emit('visibilitychange');assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'paused');
s.doc.hidden=false;s.doc.emit('visibilitychange');assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'running');
s.media.matches=true;s.media.emit('change');assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'paused');
s.media.matches=false;s.media.emit('change');assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'running');
s.byId('notice-kind').value='sale';s.byId('notice-kind').emit('change');assert.equal(s.byId('notice-copy').textContent,model.forecasts.sale.copy);
assert.equal(s.byId('notice-beta').hidden,false);assert.equal(s.byId('home-notice').dataset.fortune,'true');
s.byId('home-notice').emit('click');assert.equal(s.byId('home-dialog-title').textContent,'運命予報β — セール');assert.ok(s.byId('home-dialog-body').textContent.includes('この試作は価格を変えません'));
assert.ok(s.byId('home-notice').attributes['aria-label'].includes(model.forecasts.sale.label),'切替後も種類の読み上げ名を更新');
assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'paused','詳細閲覧中は停止');
assert.equal(s.byId('home-forecast-copy').textContent,model.forecasts.sale.copy);assert.equal(s.byId('home-forecast-copy').hidden,false);
assert.equal(s.byId('home-fortune').src,undefined,'セールには蛇の章ヒントを読み込まない');
const saleTitle=s.byId('home-dialog-title').textContent;s.api.openApp('fortune');assert.equal(s.byId('home-dialog-title').textContent,saleTitle,'帯とアプリアイコンは同じ予報を開く');
for(const button of s.forecastButtons) {
  button.emit('click');assert.equal(s.byId('notice-kind').value,button.dataset.forecastKind);
  assert.equal(s.byId('notice-copy').textContent,model.forecasts[button.dataset.forecastKind].copy);
  assert.equal(s.byId('home-notice').dataset.scrolling,String(button.dataset.forecastKind!=='none'),'予報なしは流さない');
  assert.equal(s.byId('home-fortune').hidden,button.dataset.forecastKind!=='story');
  assert.equal(button.attributes['aria-pressed'],'true');
  assert.equal(s.byId('home-task').textContent,'届いたタスクを確認する');
}
s.api.openApp('wallet');assert.equal(s.byId('forecast-options').hidden,true);assert.equal(s.byId('home-forecast-copy').hidden,true);
s.byId('home-dialog').close();s.byId('notice-kind').value='story';s.byId('notice-kind').emit('change');
s.byId('notice-copy').offsetWidth=0;s.win.emit('resize');assert.equal(s.byId('home-notice').dataset.scrolling,'false','計測できない状態では動かさない');
s.byId('notice-copy').offsetWidth=420;s.win.emit('resize');assert.equal(s.byId('home-notice').dataset.scrolling,'true','寸法の復帰後に再計測');
s.win.emit('pagehide',{persisted:true});assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'paused');
s.win.emit('pageshow');assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'running');
s.byId('home-stage').value='prologue';s.byId('home-stage').emit('change');assert.equal(s.byId('notice-kind-control').hidden,true);
for(const button of s.buttons) {button.emit('click');assert.equal(s.byId('home-dialog-title').textContent,button.dataset.homeApp==='fortune'?'運命予報β — 章のヒント':apps.apps[button.dataset.homeApp].label);assert.equal(s.byId('home-fortune').hidden,button.dataset.homeApp!=='fortune');button.img.emit('error');assert.equal(button.fallback.hidden,false);button.img.emit('load');assert.equal(button.fallback.hidden,true);}
s.api.openApp('fortune');assert.equal(s.byId('forecast-options').hidden,true,'プロローグでは他の予報を提供しない');
s.forecastButtons[1].emit('click');assert.equal(s.byId('home-dialog-title').textContent,'運命予報β — 章のヒント');
assert.equal(s.byId('home-fortune').src,s.byId('home-fortune').dataset.src);
s.byId('home-fortune').emit('load');assert.equal(s.byId('home-fortune-status').textContent,'');
const wallet=s.buttons[1];wallet.emit('focus');
s.win.emit('message',{source:s.byId('menu-wheel').contentWindow,origin:s.win.location.origin,data:{type:'solar-menu-state',selected:'save',loading:false}});assert.equal(s.byId('home-status').textContent,apps.apps.wallet.tip);
wallet.emit('blur');assert.ok(s.byId('home-status').textContent.startsWith(wheel.description('save')));
s.win.emit('message',{source:{},origin:s.win.location.origin,data:{type:'solar-menu-state',selected:'items'}});assert.ok(s.byId('home-status').textContent.startsWith(wheel.description('save')));
s.win.emit('message',{source:s.byId('menu-wheel').contentWindow,origin:'http://untrusted.invalid',data:{type:'solar-menu-state',selected:'items'}});assert.ok(s.byId('home-status').textContent.startsWith(wheel.description('save')));
s.byId('home-mystery').checked=false;s.byId('home-mystery').emit('change');assert.equal(s.byId('home-ouroboros').hidden,true);s.byId('home-dialog-title').textContent='guard';s.api.openApp('ouroboros');s.api.openApp('__proto__');assert.equal(s.byId('home-dialog-title').textContent,'guard');
s.byId('home-location').emit('error');assert.equal(s.byId('map-fallback').hidden,false);s.byId('home-location').emit('load');assert.equal(s.byId('map-fallback').hidden,true);
s.byId('map-open').emit('click');assert.equal(s.byId('home-dialog-title').textContent,'マップ');assert.equal(s.byId('map-options').hidden,false,'札を外しても窓から既存の入口が開く');
s.byId('home-map-frame').emit('error');assert.equal(s.byId('home-map-frame').hidden,true);assert.equal(s.byId('home-map').dataset.frameReady,'false');
s.byId('home-map-frame').emit('load');assert.equal(s.byId('home-map-frame').hidden,false);assert.equal(s.byId('home-map').dataset.frameReady,'true');
s.byId('home-corner-source').emit('error');assert.equal(s.byId('home-corners').dataset.ready,'false');assert.ok(s.byId('home-warning').textContent.includes('無地下地'));
s.byId('home-corner-source').emit('load');assert.equal(s.byId('home-corners').dataset.ready,'true');assert.ok(!s.byId('home-warning').textContent.includes('隅飾り'));
s.byId('map-open').emit('click');assert.equal(s.byId('map-options').hidden,false);s.mapButtons[0].emit('click');assert.ok(s.byId('home-dialog-body').textContent.includes('探索2D'));
s.byId('menu-show-frame').checked=true;s.byId('menu-show-frame').emit('change');assert.equal(s.byId('menu-device').dataset.frame,'true');
s.byId('menu-device-frame').emit('error');assert.equal(s.byId('menu-device').dataset.frame,'false');assert.equal(s.byId('menu-show-frame').disabled,true);
s.byId('menu-effects').checked=false;s.byId('menu-effects').emit('change');assert.equal(s.sent.at(-1).effects,false);assert.equal(s.byId('menu-screen').dataset.reduced,'true');
s.byId('home-screen-only').emit('click');assert.equal(s.doc.body.dataset.screenOnly,'true');assert.equal(s.doc.body.style.properties['--home-view-width'],'844px');s.byId('home-dialog').open=false;s.doc.emit('keydown',{key:'Escape'});assert.equal(s.doc.body.dataset.screenOnly,'false');
s.sticker.emit('error');assert.equal(s.byId('home-beta').hidden,true);s.sticker.emit('load');assert.equal(s.byId('home-beta').hidden,false);
s.api.destroy();s.api.destroy();s.byId('home-dialog-title').textContent='destroyed';s.buttons[0].emit('click');assert.equal(s.byId('home-dialog-title').textContent,'destroyed');
assert.equal(s.byId('menu-screen').style.properties['--ticker-play'],'paused');assert.equal(s.byId('home-notice').dataset.scrolling,'false');
const f=setup(false);f.api.openApp('wallet');assert.equal(f.byId('home-dialog').attributes.open,'');let prevented=false;f.byId('home-dialog-close').emit('click',{preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(f.byId('home-dialog').attributes.open,undefined);f.api.destroy();
for(const ready of [true,false]){const cached=setup(true,ready);assert.equal(cached.byId('home-corners').dataset.ready,String(ready));assert.equal(cached.byId('home-warning').hidden,ready);cached.api.destroy();}
const themeView=setup();
assert.equal(themeView.byId('menu-screen').style.properties['--home-surface'],'#1c1d1f');
themeView.byId('home-backing-color').value='#c7b492';themeView.byId('home-backing-color').emit('input');
themeView.byId('menu-character').value='karima';themeView.byId('menu-character').emit('change');
assert.equal(themeView.byId('home-backing-color').value,'#7194ae');assert.equal(themeView.byId('menu-screen').style.properties['--home-surface'],'#e7eef3');
assert.equal(themeView.byId('menu-screen').dataset.themeMode,'light');assert.equal(themeView.byId('home-theme-mode-control').hidden,false);
assert.equal(themeView.byId('menu-screen').style.properties['--home-ink'],'#000000');
themeView.byId('home-text-color').value='#30465a';themeView.byId('home-text-color').emit('input');
assert.equal(themeView.byId('menu-screen').style.properties['--home-ink'],'#30465a');
themeView.byId('home-surface-color').value='#19202a';themeView.byId('home-surface-color').emit('input');
themeView.byId('home-ornament-color').value='#98aabd';themeView.byId('home-ornament-color').emit('input');
assert.equal(themeView.byId('home-corner-ink').attributes['flood-color'],'#98aabd');
themeView.byId('menu-character').value='alche';themeView.byId('menu-character').emit('change');assert.equal(themeView.byId('home-backing-color').value,'#c7b492');
themeView.byId('home-theme-reset').emit('click');assert.equal(themeView.byId('home-backing-color').value,'#d3ad59');
themeView.byId('menu-character').value='karima';themeView.byId('menu-character').emit('change');assert.equal(themeView.byId('home-surface-color').value,'#19202a','他方のリセットで消さない');
themeView.byId('home-backing-color').value='bad';themeView.byId('home-backing-color').emit('input');assert.equal(themeView.byId('home-backing-color').value,'#7194ae');
themeView.byId('home-theme-mode').value='dark';themeView.byId('home-theme-mode').emit('change');
assert.equal(themeView.byId('menu-screen').dataset.themeMode,'dark');assert.equal(themeView.byId('home-surface-color').value,'#181c22');assert.equal(themeView.byId('home-text-color').value,'#eceff2');
themeView.byId('home-surface-color').value='#202630';themeView.byId('home-surface-color').emit('input');
themeView.byId('home-theme-mode').value='light';themeView.byId('home-theme-mode').emit('change');
assert.equal(themeView.byId('home-surface-color').value,'#19202a','暗い案の編集が明るい案へ漏れない');assert.equal(themeView.byId('home-text-color').value,'#30465a');
themeView.byId('home-theme-reset').emit('click');assert.equal(themeView.byId('home-surface-color').value,'#e7eef3');assert.equal(themeView.byId('home-text-color').value,'#000000');
themeView.byId('home-theme-mode').value='dark';themeView.byId('home-theme-mode').emit('change');assert.equal(themeView.byId('home-surface-color').value,'#202630','リセットは別案を消さない');
themeView.byId('menu-character').value='alche';themeView.byId('menu-character').emit('change');assert.equal(themeView.byId('home-theme-mode-control').hidden,true);
themeView.byId('home-theme-mode').value='light';themeView.byId('home-theme-mode').emit('change');assert.equal(themeView.byId('menu-screen').dataset.themeMode,'dark','アルシェを誤って明るくしない');
themeView.byId('menu-character').value='karima';themeView.byId('menu-character').emit('change');assert.equal(themeView.byId('menu-screen').dataset.themeMode,'dark','持ち主の比較案選択も保持');
themeView.byId('home-theme-mode').value='light';themeView.byId('home-theme-mode').emit('change');
themeView.byId('home-corner-size').value='48';themeView.byId('home-corner-size').emit('change');assert.equal(themeView.byId('menu-screen').style.properties['--corner-size'],'48px');
themeView.byId('home-corner-inset').value='8';themeView.byId('home-corner-inset').emit('change');assert.equal(themeView.byId('menu-screen').style.properties['--corner-inset'],'8px');
themeView.byId('home-corner-size').value='100';themeView.byId('home-corner-size').emit('change');assert.equal(themeView.byId('home-corner-size').value,'36');
themeView.byId('home-app-names').checked=false;themeView.byId('home-app-names').emit('change');assert.equal(themeView.byId('menu-screen').dataset.appNames,'false');
for(const button of themeView.buttons)assert.equal(button.attributes['aria-label'],apps.apps[button.dataset.homeApp].label);
themeView.buttons[0].emit('click');assert.equal(themeView.byId('home-dialog-title').textContent,apps.apps.preparation.label,'名前OFFでも入口は同じ');
themeView.byId('home-app-names').checked=true;themeView.byId('home-app-names').emit('change');assert.equal(themeView.byId('menu-screen').dataset.appNames,'true');
themeView.api.destroy();themeView.byId('home-app-names').checked=false;themeView.byId('home-app-names').emit('change');assert.equal(themeView.byId('menu-screen').dataset.appNames,'true','追加イベントも破棄');
themeView.byId('home-theme-mode').value='dark';themeView.byId('home-theme-mode').emit('change');assert.equal(themeView.byId('menu-screen').dataset.themeMode,'light','比較案のイベントも破棄');
// 仮想時計で「読む→流す→読む→次へ」と、停止中の時間が加算されないことを検査。
const flow=setup();flow.byId('home-stage').value='after';flow.byId('home-stage').emit('change');
flow.win.step(0);flow.win.step(4000);assert.equal(flow.byId('home-notice').dataset.tickerPhase,'before');
flow.win.step(1000);assert.equal(flow.byId('home-notice').dataset.tickerPhase,'scroll');
flow.win.step(2000);assert.equal(flow.byId('notice-track').style.properties['--ticker-offset'],'-56px');
flow.byId('home-notice').emit('pointerenter',{pointerType:'mouse'});assert.equal(flow.win.pendingFrames(),0);
flow.win.step(20000);assert.equal(flow.byId('notice-track').style.properties['--ticker-offset'],'-56px');
flow.byId('home-notice').emit('pointerleave');flow.win.step(0);flow.win.step(1000);
assert.equal(flow.byId('notice-track').style.properties['--ticker-offset'],'-84px','再開時に停止中の20秒を加算しない');
flow.byId('home-notice').emit('focus');assert.equal(flow.win.pendingFrames(),0);flow.win.step(20000);
flow.byId('home-notice').emit('blur');flow.win.step(0);flow.win.step(2000);
assert.equal(flow.byId('home-notice').dataset.tickerPhase,'after');assert.equal(flow.byId('notice-track').style.properties['--ticker-offset'],'-120px');
assert.equal(flow.byId('notice-kind').value,'story','末尾で読む間にも次へ飛ばない');
flow.win.step(2400);assert.equal(flow.byId('notice-kind').value,'sale');assert.equal(flow.byId('notice-copy').textContent,model.forecasts.sale.copy);
assert.ok(flow.byId('home-notice').attributes['aria-label'].includes(model.forecasts.sale.copy),'帯を開く／読む対象も新しい予報へ');
flow.byId('notice-copy').offsetWidth=90;flow.win.emit('resize');assert.equal(flow.byId('home-notice').dataset.scrolling,'false');
flow.win.step(0);flow.win.step(7000);assert.equal(flow.byId('home-notice').dataset.tickerPhase,'reading');assert.equal(flow.byId('notice-kind').value,'sale');
flow.win.step(1000);assert.equal(flow.byId('notice-kind').value,'support');
flow.win.step(0);flow.win.step(8000);assert.equal(flow.byId('notice-kind').value,'encounter');
flow.win.step(0);flow.win.step(8000);assert.equal(flow.byId('notice-kind').value,'story','4件の末尾から先頭へ循環');
flow.byId('home-notice').emit('click');assert.equal(flow.win.pendingFrames(),0);flow.win.step(90000);assert.equal(flow.byId('notice-kind').value,'story','詳細中は順送りも停止');
flow.byId('home-dialog').close();flow.byId('notice-scroll').checked=false;flow.byId('notice-scroll').emit('change');assert.equal(flow.win.pendingFrames(),0);
flow.byId('notice-scroll').checked=true;flow.byId('notice-scroll').emit('change');flow.doc.hidden=true;flow.doc.emit('visibilitychange');assert.equal(flow.win.pendingFrames(),0);
flow.doc.hidden=false;flow.doc.emit('visibilitychange');flow.media.matches=true;flow.media.emit('change');assert.equal(flow.win.pendingFrames(),0);assert.equal(flow.byId('notice-track').style.properties['--ticker-offset'],'0px');
flow.media.matches=false;flow.media.emit('change');flow.byId('notice-before').value='2';flow.byId('notice-before').emit('change');flow.byId('notice-after').value='1';flow.byId('notice-after').emit('change');
flow.win.step(0);flow.win.step(3000);assert.equal(flow.byId('notice-kind').value,'sale','読む間の調整を短文にも反映');
flow.byId('notice-after').value='0';flow.byId('notice-after').emit('change');assert.equal(flow.byId('notice-after').value,'3','不正な秒数は初期値へ戻す');
flow.byId('notice-kind').value='none';flow.byId('notice-kind').emit('change');assert.equal(flow.win.pendingFrames(),0);flow.win.step(90000);assert.equal(flow.byId('notice-kind').value,'none');
flow.byId('notice-kind').value='story';flow.byId('notice-kind').emit('change');flow.byId('home-stage').value='prologue';flow.byId('home-stage').emit('change');assert.equal(flow.win.pendingFrames(),0,'通信は順送りしない');
flow.byId('home-stage').value='after';flow.byId('home-stage').emit('change');flow.win.emit('pagehide',{persisted:true});assert.equal(flow.win.pendingFrames(),0);flow.win.emit('pageshow');assert.equal(flow.win.pendingFrames(),1);
flow.byId('home-notice').emit('pointerenter',{pointerType:'touch'});assert.equal(flow.win.pendingFrames(),1,'タッチのpointerenterでhover停止が残らない');
flow.byId('notice-copy').offsetWidth=0;flow.win.emit('resize');assert.equal(flow.win.pendingFrames(),0,'未計測なら順送りせず待つ');
flow.byId('notice-copy').offsetWidth=90;flow.win.emit('resize');assert.equal(flow.win.pendingFrames(),1);
flow.api.destroy();assert.equal(flow.win.pendingFrames(),0,'破棄時に次フレームを取り消す');flow.win.step(90000);
const fontFit=setup(true,null,310);fontFit.byId('home-stage').value='after';fontFit.byId('home-stage').emit('change');
assert.equal(fontFit.byId('notice-copy').style.properties['--ticker-font'],'13px');
assert.equal(fontFit.byId('notice-font-size').textContent,'13');assert.equal(fontFit.byId('home-notice').dataset.scrolling,'false','縮めて収まれば静止する');
assert.equal(fontFit.byId('notice-measure').textContent,fontFit.byId('notice-copy').textContent);
fontFit.win.step(0);fontFit.win.step(8000);assert.equal(fontFit.byId('notice-kind').value,'sale','自動調整後も次の予報へ進む');
fontFit.byId('notice-copy').offsetWidth=450;fontFit.win.emit('resize');
assert.equal(fontFit.byId('notice-copy').style.properties['--ticker-font'],'12px');assert.equal(fontFit.byId('home-notice').dataset.scrolling,'true','12pxでも長い文は流す');
fontFit.win.step(0);fontFit.win.step(6000);assert.equal(fontFit.byId('notice-track').style.properties['--ticker-offset'],'-28px','縮小後の距離でも速度は変えない');
fontFit.win.emit('resize');assert.equal(fontFit.byId('notice-track').style.properties['--ticker-offset'],'-28px','同じ寸法の再計測で毎回先頭へ戻さない');
fontFit.byId('notice-copy').offsetWidth=280;fontFit.win.emit('resize');assert.equal(fontFit.byId('notice-copy').style.properties['--ticker-font'],'13.5px','短い文や幅の復帰で元のサイズへ');
fontFit.byId('notice-font').value='12.5';fontFit.byId('notice-font').emit('change');assert.equal(fontFit.byId('notice-copy').style.properties['--ticker-font'],'12.5px');
fontFit.byId('notice-font').value='11';fontFit.byId('notice-font').emit('change');assert.equal(fontFit.byId('notice-font').value,'13.5');
fontFit.byId('notice-copy').offsetWidth=310;fontFit.byId('notice-font-auto').checked=false;fontFit.byId('notice-font-auto').emit('change');
assert.equal(fontFit.byId('notice-copy').style.properties['--ticker-font'],'13.5px');assert.equal(fontFit.byId('home-notice').dataset.scrolling,'true','自動調整OFFなら選んだサイズを固定');
fontFit.byId('notice-font-auto').checked=true;fontFit.byId('notice-font-auto').emit('change');assert.equal(fontFit.byId('home-notice').dataset.scrolling,'false');
fontFit.byId('notice-copy').offsetWidth=0;fontFit.win.emit('resize');assert.equal(fontFit.win.pendingFrames(),0);
fontFit.byId('notice-copy').offsetWidth=450;fontFit.byId('home-stage').value='prologue';fontFit.byId('home-stage').emit('change');assert.equal(fontFit.byId('notice-copy').style.properties['--ticker-font'],'13.5px','プロローグ通信の書体サイズは変えない');
fontFit.api.destroy();assert.equal(fontFit.win.pendingFrames(),0);
const widerBand=setup(true,null,450);widerBand.byId('home-stage').value='after';widerBand.byId('home-stage').emit('change');
widerBand.byId('notice-font').value='12';widerBand.byId('notice-font').emit('change');
assert.equal(widerBand.byId('home-notice').dataset.scrolling,'true','仮の狭い幅では12pxでも流す');
widerBand.byId('notice-viewport').clientWidth=410;widerBand.win.emit('resize');
assert.equal(widerBand.byId('notice-copy').style.properties['--ticker-font'],'12px');
assert.equal(widerBand.byId('home-notice').dataset.scrolling,'false','本文幅が広がり収まれば静止へ戻る（実フォント幅の測定ではない）');
assert.equal(widerBand.byId('notice-track').style.properties['--ticker-offset'],'0px');
widerBand.byId('home-notice').emit('click');assert.equal(widerBand.byId('home-dialog-title').textContent,'運命予報β — 章のヒント');
assert.equal(widerBand.byId('home-forecast-copy').textContent,model.forecasts.story.copy,'種類を帯から外しても詳細の全文は維持');
widerBand.api.destroy();assert.equal(widerBand.win.pendingFrames(),0);
async function verifySettings() {
  const save=setup();assert.equal(save.writes.length,0,'初期表示だけでは保存済みと偽らず上書きしない');
  save.byId('home-theme-recover').emit('click');
  assert.equal(save.byId('menu-character').value,'karima');assert.equal(save.byId('menu-screen').dataset.themeMode,'light');
  for(const [key,id] of [['background','home-surface-color'],['text','home-text-color'],['backing','home-backing-color'],['ornament','home-ornament-color']])assert.equal(save.byId(id).value,model.karimaRecoveredTheme[key]);
  assert.equal(save.byId('home-corner-size').value,'36');assert.equal(save.byId('home-corner-inset').value,'0');
  const raw=save.storage.get(model.settingsStorageKey),saved=model.readSettings(raw);
  assert.equal(saved.selectedOwner,'karima');assert.deepEqual(saved.ownerThemes.karima.light,model.karimaRecoveredTheme);
  assert.equal(save.byId('home-settings-json').value,raw);assert.deepEqual(model.readSettings(JSON.stringify(saved)),saved);
  assert.equal(model.settings(null),null);
  for(const mutate of [v=>v.schema='other',v=>v.referenceResolution.width=1,v=>v.ownerModes.alche='light',v=>v.selectedOwner='__proto__',v=>v.ownerThemes.karima.light.text='url(bad)',v=>v.corner.size=100,v=>v.corner.inset=-1,v=>v.preview.phase='dusk',v=>v.showAppNames='false',v=>v.forecast.before=0,v=>v.forecast.fontLimit=11]) {
    const invalid=JSON.parse(raw);mutate(invalid);assert.throws(()=>model.readSettings(JSON.stringify(invalid)));
  }
  assert.throws(()=>model.readSettings('{'));assert.throws(()=>model.readSettings('x'.repeat(65537)));
  const loaded=setup(true,null,null,{data:save.storage});assert.equal(loaded.byId('menu-screen').dataset.owner,'karima');assert.equal(loaded.byId('home-text-color').value,'#000000');
  assert.ok(loaded.byId('home-save-status').textContent.includes('復元'));assert.equal(loaded.writes.length,0);
  loaded.byId('home-settings-import').value='{bad';loaded.byId('home-settings-import-button').emit('click');assert.equal(loaded.byId('home-surface-color').value,'#f6fafe');assert.equal(loaded.writes.length,0,'読めないJSONで今の状態と自動保存を消さない');
  loaded.byId('home-app-names').checked=false;loaded.byId('home-app-names').emit('change');
  loaded.byId('notice-before').value='7';loaded.byId('notice-before').emit('change');
  loaded.byId('menu-phase').value='night';loaded.byId('menu-phase').emit('change');
  const adjusted=model.readSettings(loaded.storage.get(model.settingsStorageKey));assert.equal(adjusted.showAppNames,false);assert.equal(adjusted.forecast.before,7);assert.equal(adjusted.preview.phase,'night');
  const imported=setup();imported.byId('home-settings-import').value=JSON.stringify(adjusted);imported.byId('home-settings-import-button').emit('click');
  assert.equal(imported.byId('menu-screen').dataset.appNames,'false');assert.equal(imported.byId('notice-before').value,'7');assert.equal(imported.byId('menu-phase').value,'night');assert.ok(imported.byId('home-save-status').textContent.includes('読み込み'));
  imported.byId('home-settings-save').emit('click');const url=[...imported.urls.keys()][0];assert.equal(imported.elements.at(-1).download,'menu-home-settings.json');assert.equal(imported.elements.at(-1).clicked,true);assert.equal(imported.elements.at(-1).removed,true);
  assert.deepEqual(model.readSettings(await imported.urls.get(url).text()),adjusted);imported.win.flushTimeouts();assert.ok(imported.revoked.includes(url));
  imported.byId('home-settings-save').emit('click');const pending=[...imported.urls.keys()][0];imported.api.destroy();assert.ok(imported.revoked.includes(pending));assert.equal(imported.timers.size,0);
  const denied=setup(true,null,null,{getterFail:true});denied.byId('home-theme-recover').emit('click');assert.ok(denied.byId('home-save-status').textContent.includes('自動保存できません'));denied.byId('home-settings-save').emit('click');assert.equal(denied.elements.at(-1).clicked,true,'保存禁止でもJSONダウンロードは独立');
  await denied.byId('home-settings-copy').emitAsync('click');assert.equal(denied.byId('home-settings-json').selected,true,'clipboard禁止は手動選択へ');
  let copied;denied.win.navigator={clipboard:{writeText:async text=>{copied=text;}}};await denied.byId('home-settings-copy').emitAsync('click');assert.equal(model.readSettings(copied).selectedOwner,'karima');
  const corruptData=new Map([[model.settingsStorageKey,'{corrupt']]),corrupt=setup(true,null,null,{data:corruptData});assert.equal(corruptData.get(model.settingsStorageKey),'{corrupt');assert.ok(corrupt.byId('home-save-status').textContent.includes('上書きしていません'));
  const quota=setup(true,null,null,{writeFail:true});quota.byId('home-theme-recover').emit('click');assert.ok(quota.byId('home-save-status').textContent.includes('自動保存できません'));
  const fileView=setup();fileView.byId('home-settings-file').files=[{size:raw.length,text:async()=>raw}];await fileView.byId('home-settings-file').emitAsync('change');assert.equal(fileView.byId('home-surface-color').value,'#f6fafe');assert.equal(fileView.byId('home-settings-file').disabled,false);assert.equal(fileView.byId('home-settings-file').value,'');
  const beforeInvalid=fileView.storage.get(model.settingsStorageKey);fileView.byId('home-settings-file').files=[{size:65537,text:()=>{throw new Error('must not read');}}];await fileView.byId('home-settings-file').emitAsync('change');assert.equal(fileView.storage.get(model.settingsStorageKey),beforeInvalid);assert.ok(fileView.byId('home-save-status').textContent.includes('大きすぎ'));
  fileView.byId('home-settings-file').files=[{size:1,text:async()=>{throw new Error('file read failed');}}];await fileView.byId('home-settings-file').emitAsync('change');assert.equal(fileView.byId('home-settings-file').disabled,false);assert.equal(fileView.storage.get(model.settingsStorageKey),beforeInvalid);
  const delayed=setup();let finish;delayed.byId('home-settings-file').files=[{size:raw.length,text:()=>new Promise(resolve=>{finish=resolve;})}];const task=delayed.byId('home-settings-file').emitAsync('change');delayed.api.destroy();finish(raw);await task;assert.equal(delayed.writes.length,0,'破棄後の読み込みは反映・保存しない');
  const tickerSave=loaded.writes.length;loaded.byId('home-stage').value='after';loaded.byId('home-stage').emit('change');loaded.win.step(0);loaded.win.step(90000);assert.equal(loaded.writes.length,tickerSave+1,'自動テロップ切替を保存ループにしない');
  for(const view of [save,loaded,denied,corrupt,quota,fileView])view.api.destroy();
  console.log('PASS: 配色復元・自動保存／再読込・人物／案別保持・JSON保存／コピー／ファイルと貼付読込・破損／別形式／範囲外／保存禁止／読込失敗・非同期破棄とURL解放。既存のマップ入口・予報動作も成功。描画QA未実施。');
}
verifySettings().catch(error=>{console.error(error);process.exitCode=1;});
