'use strict';
const assert = require('node:assert/strict');
const settings = require('./dialogue-settings.js');
assert.deepEqual(settings.normalize(null), settings.defaults);
assert.deepEqual(settings.parse(settings.serialize(settings.defaults)), settings.defaults);
const input = { width: 660, height: 154, transparency: 38, radius: 8, panelColor: '#ABCDEF', borderColor: '#123456', textColor: '#FFFFFF', ornament: 'small' };
const result = settings.normalize(input);
assert.equal(result.panelColor, '#abcdef');
assert.equal(input.panelColor, '#ABCDEF');
assert.deepEqual(settings.parse(settings.serialize(input)), result);
assert.equal(settings.normalize({ width: -1, height: 10000, transparency: -40, radius: 99 }).width, 480);
assert.equal(settings.normalize({ width: -1, height: 10000, transparency: -40, radius: 99 }).height, 180);
assert.equal(settings.normalize({ width: NaN, height: Infinity, panelColor: 'red', textColor: 'url(x)' }).width, 796);
assert.equal(settings.normalize({ width: '650', ornament: 'invalid' }).ornament, 'medium');
assert.equal(settings.rgba('#0b1822', 100), 'rgba(11,24,34,0)');
assert.equal(settings.rgba('#0b1822', 0), 'rgba(11,24,34,1)');
assert.equal(settings.rgba('#0b1822', 4), 'rgba(11,24,34,0.96)');
for (const invalid of ['{', 'null', '[]', '{"version":2,"settings":{}}', '{"version":1,"settings":{}}']) assert.throws(() => settings.parse(invalid));
assert.throws(() => settings.parse(JSON.stringify({ version: 1, settings: { ...settings.defaults, width: '600' } })));
assert.throws(() => settings.parse(JSON.stringify({ version: 1, settings: { ...settings.defaults, textColor: 'invalid' } })));
assert.throws(() => settings.parse(JSON.stringify({ version: 1, settings: { ...settings.defaults, ornament: 'giant' } })));
assert.equal(settings.parse(JSON.stringify({ version: 1, settings: { ...settings.defaults, width: 9999 } })).width, 796);
assert.deepEqual(Object.keys(settings.normalize({ ...settings.defaults, unknown: true })).sort(), Object.keys(settings.defaults).sort());
const portrait = settings.normalize({ ...settings.portraitTrial, width: 900, height: 999 }, 'portraits');
assert.equal(portrait.width, 440);
assert.equal(portrait.height, 156);
assert.deepEqual(settings.parse(settings.serialize(settings.portraitTrial, 'portraits'), 'portraits'), settings.portraitTrial);
assert.equal(JSON.parse(settings.serialize(settings.portraitTrial, 'portraits')).presentation, 'portraits-top');
assert.notEqual(settings.portraitStorageKey, settings.corridorStorageKey);
const provisional = require('./dialogue-portrait-provisional-settings.json');
assert.deepEqual(settings.parse(JSON.stringify(provisional), 'portraits'), settings.portraitTrial);
assert.equal(settings.portraitTrial.height, 100);
assert.equal(settings.portraitTrial.panelColor, '#131d34');
assert.equal(settings.normalize(settings.corridorTrial).width, 796);
console.log('dialogue-settings: all tests passed');
